name: test-build
run-name: Building the java server
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Test with Maven
        run: mvn --batch-mode --update-snapshots clean package
      - name: Set Release version env variable
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Show Release version
        run: |
          echo "Release version: ${{ env.RELEASE_VERSION }}"
      - name: Move build files to current directory
        run: |
          ls -la
          mv target/*.jar .
      - name: Create draft release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ env.RELEASE_VERSION }}"
          draft: true
          prerelease: false
          title: "Release v${{ env.RELEASE_VERSION }}"
          files: |
            arduino-server-${{ env.RELEASE_VERSION }}.jar
